/**
 * GitHub Actions workflow generator
 *
 * After InfraReady successfully deploys ECS + ECR, we generate a
 * `.github/workflows/deploy.yml` file that the customer adds to their repo.
 *
 * The workflow:
 *   1. Triggers on push to the configured branch
 *   2. Authenticates to the customer's ECR using OIDC (no long-lived AWS keys)
 *   3. Builds a Docker image from their repo root (or a custom Dockerfile path)
 *   4. Pushes to their ECR repository
 *   5. Forces a new ECS deployment — ECS pulls the new image automatically
 *
 * Why OIDC instead of access keys:
 *   - No long-lived AWS credentials stored in GitHub Secrets
 *   - SOC2-friendly: no static credentials that can be leaked or rotated
 *   - GitHub OIDC is free and well-supported in AWS IAM
 *
 * The customer needs to:
 *   1. Add this file to their repo at `.github/workflows/deploy.yml`
 *   2. Create an IAM OIDC provider for GitHub Actions in their AWS account
 *      (our OpenTofu security module can add this — flag for future sprint)
 *   3. Add the generated IAM role ARN as `AWS_DEPLOY_ROLE_ARN` in GitHub Secrets
 */

export interface WorkflowConfig {
  /** AWS account ID — embedded in ECR URL */
  awsAccountId: string;
  /** AWS region where ECR and ECS live */
  awsRegion: string;
  /** Full ECR repository URL (without tag), e.g. 123456789.dkr.ecr.us-east-1.amazonaws.com/myapp-prod */
  ecrRepositoryUrl: string;
  /** ECS cluster name */
  ecsClusterName: string;
  /** ECS service name */
  ecsServiceName: string;
  /** Branch to deploy on push — defaults to "main" */
  branch?: string;
  /** Path to Dockerfile relative to repo root — defaults to "." */
  dockerfilePath?: string;
  /** Docker build context relative to repo root — defaults to "." */
  buildContext?: string;
  /** OIDC deploy role ARN — baked into the workflow, no GitHub Secret needed */
  deployRoleArn?: string;
}

/**
 * Generates the YAML content for the GitHub Actions deploy workflow.
 * Returns a string — write it to `.github/workflows/deploy.yml` in the customer's repo.
 */
export function generateGitHubWorkflow(config: WorkflowConfig): string {
  const branch         = config.branch ?? "main";
  const dockerfilePath = config.dockerfilePath ?? ".";
  const buildContext   = config.buildContext ?? ".";

  // Derive the ECR registry hostname from the repo URL
  // e.g. "123456789.dkr.ecr.us-east-1.amazonaws.com/myapp-prod" → "123456789.dkr.ecr.us-east-1.amazonaws.com"
  const ecrRegistry = config.ecrRepositoryUrl.split("/")[0];

  return `# .github/workflows/deploy.yml
# Generated by InfraReady — https://infraready.io
#
# This workflow builds your Docker image and deploys it to AWS ECS.
#
# One-time setup required:
#   1. Add this file to your repo at .github/workflows/deploy.yml
#   2. In your AWS account, ensure the GitHub OIDC provider exists:
#      aws iam create-open-id-connect-provider \\
#        --url https://token.actions.githubusercontent.com \\
#        --client-id-list sts.amazonaws.com \\
#        --thumbprint-list 6938fd4d98bab03faadb97b34396831e3780aea1
#   3. Add this GitHub Secret to your repo:
#      AWS_DEPLOY_ROLE_ARN = <the IAM role ARN that trusts GitHub OIDC>
#      (Your InfraReady project shows this in the deployment outputs)

name: Deploy to ECS

on:
  push:
    branches:
      - ${branch}

# Limit to one concurrent deployment per branch — cancel in-progress runs
# if a new push arrives so we always ship the latest code.
concurrency:
  group: deploy-\${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write   # Required for OIDC authentication
  contents: read

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC — no stored keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${config.deployRoleArn ?? "${{ secrets.AWS_DEPLOY_ROLE_ARN }}"}
          aws-region: ${config.awsRegion}
          # Session duration 15 min is enough for a build + push + ECS update
          role-session-duration: 900

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: "${config.awsAccountId}"

      - name: Set image tag
        id: image-tag
        run: |
          # Use the short git SHA as the image tag for traceability
          echo "tag=${config.ecrRepositoryUrl}:\${{ github.sha }}" >> "$GITHUB_OUTPUT"
          echo "latest=${config.ecrRepositoryUrl}:latest" >> "$GITHUB_OUTPUT"

      - name: Build Docker image
        run: |
          docker build \\
            -f ${dockerfilePath}/Dockerfile \\
            -t "\${{ steps.image-tag.outputs.tag }}" \\
            -t "\${{ steps.image-tag.outputs.latest }}" \\
            --label "git.commit=\${{ github.sha }}" \\
            --label "git.ref=\${{ github.ref }}" \\
            --label "build.run=\${{ github.run_id }}" \\
            --cache-from "\${{ steps.image-tag.outputs.latest }}" \\
            ${buildContext}

      - name: Push image to ECR
        run: |
          docker push "\${{ steps.image-tag.outputs.tag }}"
          docker push "\${{ steps.image-tag.outputs.latest }}"

      - name: Deploy to ECS
        run: |
          aws ecs update-service \\
            --cluster ${config.ecsClusterName} \\
            --service ${config.ecsServiceName} \\
            --force-new-deployment \\
            --region ${config.awsRegion} \\
            --query 'service.deployments[0].{status:status,desiredCount:desiredCount}' \\
            --output table

      - name: Wait for ECS stability
        run: |
          echo "Waiting for ECS service to stabilize (timeout: 10 min)..."
          aws ecs wait services-stable \\
            --cluster ${config.ecsClusterName} \\
            --services ${config.ecsServiceName} \\
            --region ${config.awsRegion}
          echo "Deployment stable."

      - name: Summary
        if: always()
        run: |
          echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "| | |" >> $GITHUB_STEP_SUMMARY
          echo "|---|---|" >> $GITHUB_STEP_SUMMARY
          echo "| Commit | \`\${{ github.sha }}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| Image | \`\${{ steps.image-tag.outputs.tag }}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| Cluster | \`${config.ecsClusterName}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| Service | \`${config.ecsServiceName}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| Region | \`${config.awsRegion}\` |" >> $GITHUB_STEP_SUMMARY
`;
}

/**
 * Builds the WorkflowConfig from the flat outputs object saved in Supabase
 * after a successful ECS deployment.
 *
 * Returns null if required outputs are missing (e.g. ECS module was not deployed).
 */
export function workflowConfigFromOutputs(
  outputs: Record<string, unknown>,
  awsAccountId: string,
  awsRegion: string,
  branch = "main"
): WorkflowConfig | null {
  const ecrUrl      = outputs.ecr_url as string | undefined;
  const clusterName = outputs.cluster_name as string | undefined;
  const serviceName = outputs.service_name as string | undefined;

  if (!ecrUrl || !clusterName || !serviceName) {
    return null;
  }

  return {
    awsAccountId,
    awsRegion,
    ecrRepositoryUrl: ecrUrl,
    ecsClusterName:   clusterName,
    ecsServiceName:   serviceName,
    branch,
    // OIDC role ARN baked in — no need to store as GitHub Secret
    deployRoleArn: outputs.github_deploy_role_arn as string | undefined,
  };
}

// ─── Static site workflow ─────────────────────────────────────────────────────

export interface StaticWorkflowConfig {
  /** AWS region */
  awsRegion: string;
  /** S3 bucket name to sync to */
  s3BucketName: string;
  /** CloudFront distribution ID for cache invalidation */
  cloudfrontDistributionId: string;
  /** OIDC deploy role ARN — baked in, NOT stored as a secret */
  deployRoleArn: string;
  /** Branch to deploy on push — defaults to "main" */
  branch?: string;
  /** Build command — e.g. "npm ci && npm run build". Empty = no build step */
  buildCommand?: string;
  /** Directory to sync to S3 — e.g. "dist", "build", "out", "." */
  outputDirectory?: string;
  /** Node version for the build (if buildCommand uses npm) */
  nodeVersion?: string;
}

/**
 * Generates a GitHub Actions workflow for static site deployment.
 * Builds the project, syncs to S3, invalidates CloudFront cache.
 * Uses OIDC — no long-lived AWS credentials stored in GitHub Secrets.
 */
export function generateStaticWorkflow(config: StaticWorkflowConfig): string {
  const branch    = config.branch ?? "main";
  const outputDir = config.outputDirectory ?? "dist";
  const nodeVer   = config.nodeVersion ?? "20";

  const buildStep = config.buildCommand ? `
      - name: Install & Build
        run: ${config.buildCommand}
` : `
      - name: No build step needed
        run: echo "Static site — no build required"
`;

  return `# .github/workflows/deploy.yml
# Generated by InfraReady — https://infraready.io
#
# Deploys your static site to S3 + CloudFront on every push to ${branch}.
# Uses AWS OIDC — no long-lived credentials stored anywhere.

name: Deploy to S3 + CloudFront

on:
  push:
    branches:
      - ${branch}

concurrency:
  group: deploy-\${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
${config.buildCommand ? `
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "${nodeVer}"
          cache: "npm"
` : ""}
      - name: Configure AWS credentials (OIDC — no stored keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${config.deployRoleArn}
          aws-region: ${config.awsRegion}
          role-session-duration: 900
${buildStep}
      - name: Sync to S3
        run: |
          aws s3 sync ./${outputDir} s3://${config.s3BucketName} \\
            --delete \\
            --cache-control "public, max-age=31536000, immutable" \\
            --exclude "*.html" \\
            --exclude "*.json"
          # HTML and JSON: no long-term cache (always re-validate)
          aws s3 sync ./${outputDir} s3://${config.s3BucketName} \\
            --delete \\
            --cache-control "public, max-age=0, must-revalidate" \\
            --include "*.html" \\
            --include "*.json"

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \\
            --distribution-id ${config.cloudfrontDistributionId} \\
            --paths "/*"

      - name: Summary
        if: always()
        run: |
          echo "## Deploy Summary" >> $GITHUB_STEP_SUMMARY
          echo "| | |" >> $GITHUB_STEP_SUMMARY
          echo "|---|---|" >> $GITHUB_STEP_SUMMARY
          echo "| Commit | \`\${{ github.sha }}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| Bucket | \`${config.s3BucketName}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| CloudFront | \`${config.cloudfrontDistributionId}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| Region | \`${config.awsRegion}\` |" >> $GITHUB_STEP_SUMMARY
`;
}

/**
 * Builds StaticWorkflowConfig from deployment outputs.
 * Returns null if the required outputs are missing.
 */
export function staticWorkflowConfigFromOutputs(
  outputs: Record<string, unknown>,
  awsRegion: string,
  branch = "main",
  buildCommand?: string,
  outputDirectory?: string,
): StaticWorkflowConfig | null {
  const bucketName      = outputs.bucket_name as string | undefined;
  const distributionId  = outputs.cloudfront_distribution_id as string | undefined;
  const deployRoleArn   = outputs.github_deploy_role_arn as string | undefined;

  if (!bucketName || !distributionId || !deployRoleArn) return null;

  return {
    awsRegion,
    s3BucketName:             bucketName,
    cloudfrontDistributionId: distributionId,
    deployRoleArn,
    branch,
    buildCommand,
    outputDirectory,
  };
}
