/**
 * GitHub Actions workflow generator
 *
 * After InfraReady successfully deploys ECS + ECR, we generate a
 * `.github/workflows/deploy.yml` file that the customer adds to their repo.
 *
 * The workflow:
 *   1. Triggers on push to the configured branch
 *   2. Authenticates to the customer's ECR using OIDC (no long-lived AWS keys)
 *   3. Builds a Docker image from their repo root (or a custom Dockerfile path)
 *   4. Pushes to their ECR repository
 *   5. Forces a new ECS deployment — ECS pulls the new image automatically
 *
 * Why OIDC instead of access keys:
 *   - No long-lived AWS credentials stored in GitHub Secrets
 *   - SOC2-friendly: no static credentials that can be leaked or rotated
 *   - GitHub OIDC is free and well-supported in AWS IAM
 *
 * The customer needs to:
 *   1. Add this file to their repo at `.github/workflows/deploy.yml`
 *   2. Create an IAM OIDC provider for GitHub Actions in their AWS account
 *      (our OpenTofu security module can add this — flag for future sprint)
 *   3. Add the generated IAM role ARN as `AWS_DEPLOY_ROLE_ARN` in GitHub Secrets
 */

export interface WorkflowConfig {
  /** AWS account ID — embedded in ECR URL */
  awsAccountId: string;
  /** AWS region where ECR and ECS live */
  awsRegion: string;
  /** Full ECR repository URL (without tag), e.g. 123456789.dkr.ecr.us-east-1.amazonaws.com/myapp-prod */
  ecrRepositoryUrl: string;
  /** ECS cluster name */
  ecsClusterName: string;
  /** ECS service name */
  ecsServiceName: string;
  /** Branch to deploy on push — defaults to "main" */
  branch?: string;
  /** Path to Dockerfile relative to repo root — defaults to "." */
  dockerfilePath?: string;
  /** Docker build context relative to repo root — defaults to "." */
  buildContext?: string;
}

/**
 * Generates the YAML content for the GitHub Actions deploy workflow.
 * Returns a string — write it to `.github/workflows/deploy.yml` in the customer's repo.
 */
export function generateGitHubWorkflow(config: WorkflowConfig): string {
  const branch         = config.branch ?? "main";
  const dockerfilePath = config.dockerfilePath ?? ".";
  const buildContext   = config.buildContext ?? ".";

  // Derive the ECR registry hostname from the repo URL
  // e.g. "123456789.dkr.ecr.us-east-1.amazonaws.com/myapp-prod" → "123456789.dkr.ecr.us-east-1.amazonaws.com"
  const ecrRegistry = config.ecrRepositoryUrl.split("/")[0];

  return `# .github/workflows/deploy.yml
# Generated by InfraReady — https://infraready.io
#
# This workflow builds your Docker image and deploys it to AWS ECS.
#
# One-time setup required:
#   1. Add this file to your repo at .github/workflows/deploy.yml
#   2. In your AWS account, ensure the GitHub OIDC provider exists:
#      aws iam create-open-id-connect-provider \\
#        --url https://token.actions.githubusercontent.com \\
#        --client-id-list sts.amazonaws.com \\
#        --thumbprint-list 6938fd4d98bab03faadb97b34396831e3780aea1
#   3. Add this GitHub Secret to your repo:
#      AWS_DEPLOY_ROLE_ARN = <the IAM role ARN that trusts GitHub OIDC>
#      (Your InfraReady project shows this in the deployment outputs)

name: Deploy to ECS

on:
  push:
    branches:
      - ${branch}

# Limit to one concurrent deployment per branch — cancel in-progress runs
# if a new push arrives so we always ship the latest code.
concurrency:
  group: deploy-\${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write   # Required for OIDC authentication
  contents: read

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: \${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${config.awsRegion}
          # Session duration 15 min is enough for a build + push + ECS update
          role-session-duration: 900

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: "${config.awsAccountId}"

      - name: Set image tag
        id: image-tag
        run: |
          # Use the short git SHA as the image tag for traceability
          echo "tag=${config.ecrRepositoryUrl}:\${{ github.sha }}" >> "$GITHUB_OUTPUT"
          echo "latest=${config.ecrRepositoryUrl}:latest" >> "$GITHUB_OUTPUT"

      - name: Build Docker image
        run: |
          docker build \\
            -f ${dockerfilePath}/Dockerfile \\
            -t "\${{ steps.image-tag.outputs.tag }}" \\
            -t "\${{ steps.image-tag.outputs.latest }}" \\
            --label "git.commit=\${{ github.sha }}" \\
            --label "git.ref=\${{ github.ref }}" \\
            --label "build.run=\${{ github.run_id }}" \\
            --cache-from "\${{ steps.image-tag.outputs.latest }}" \\
            ${buildContext}

      - name: Push image to ECR
        run: |
          docker push "\${{ steps.image-tag.outputs.tag }}"
          docker push "\${{ steps.image-tag.outputs.latest }}"

      - name: Deploy to ECS
        run: |
          aws ecs update-service \\
            --cluster ${config.ecsClusterName} \\
            --service ${config.ecsServiceName} \\
            --force-new-deployment \\
            --region ${config.awsRegion} \\
            --query 'service.deployments[0].{status:status,desiredCount:desiredCount}' \\
            --output table

      - name: Wait for ECS stability
        run: |
          echo "Waiting for ECS service to stabilize (timeout: 10 min)..."
          aws ecs wait services-stable \\
            --cluster ${config.ecsClusterName} \\
            --services ${config.ecsServiceName} \\
            --region ${config.awsRegion}
          echo "Deployment stable."

      - name: Summary
        if: always()
        run: |
          echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "| | |" >> $GITHUB_STEP_SUMMARY
          echo "|---|---|" >> $GITHUB_STEP_SUMMARY
          echo "| Commit | \`\${{ github.sha }}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| Image | \`\${{ steps.image-tag.outputs.tag }}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| Cluster | \`${config.ecsClusterName}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| Service | \`${config.ecsServiceName}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| Region | \`${config.awsRegion}\` |" >> $GITHUB_STEP_SUMMARY
`;
}

/**
 * Builds the WorkflowConfig from the flat outputs object saved in Supabase
 * after a successful ECS deployment.
 *
 * Returns null if required outputs are missing (e.g. ECS module was not deployed).
 */
export function workflowConfigFromOutputs(
  outputs: Record<string, unknown>,
  awsAccountId: string,
  awsRegion: string,
  branch = "main"
): WorkflowConfig | null {
  const ecrUrl      = outputs.ecr_url as string | undefined;
  const clusterName = outputs.cluster_name as string | undefined;
  const serviceName = outputs.service_name as string | undefined;

  if (!ecrUrl || !clusterName || !serviceName) {
    return null;
  }

  return {
    awsAccountId,
    awsRegion,
    ecrRepositoryUrl: ecrUrl,
    ecsClusterName:   clusterName,
    ecsServiceName:   serviceName,
    branch,
  };
}
