"use client";

import { useState } from "react";
import {
  Copy, Check, Download, Database, Globe, Server,
  HardDrive, Shield, ExternalLink, ChevronDown, ChevronUp,
} from "lucide-react";

interface ResourceOutputs {
  // VPC
  vpc_id?: string;
  public_subnet_ids?: string[];
  private_subnet_ids?: string[];
  // RDS
  db_endpoint?: string;
  db_port?: number;
  db_name?: string;
  db_secret_arn?: string;
  // ECS
  app_url?: string;
  ecr_url?: string;
  cluster_name?: string;
  service_name?: string;
  log_group?: string;
  task_role_arn?: string;
  execution_role_arn?: string;
  // Storage
  cdn_url?: string;
  bucket_name?: string;
  bucket_arn?: string;
  // Security
  alerts_topic_arn?: string;
  // GitHub
  github_workflow_yaml?: string;
}

interface Props {
  outputs: ResourceOutputs;
  projectName: string;
  awsRegion: string;
  awsAccountId?: string | null;
}

function CopyButton({ value }: { value: string }) {
  const [copied, setCopied] = useState(false);
  const copy = async () => {
    await navigator.clipboard.writeText(value);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };
  return (
    <button onClick={copy} className="ml-2 text-gray-500 hover:text-sky-400 transition-colors shrink-0" title="Copy">
      {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
    </button>
  );
}

function OutputRow({ label, value, mono = true }: { label: string; value: string; mono?: boolean }) {
  return (
    <div className="flex items-start justify-between py-2 border-b border-white/[0.04] last:border-0">
      <span className="text-xs text-gray-500 shrink-0 w-36">{label}</span>
      <div className="flex items-center min-w-0 flex-1">
        <span className={`text-xs text-gray-300 truncate ${mono ? "font-mono" : ""}`}>{value}</span>
        <CopyButton value={value} />
      </div>
    </div>
  );
}

function ResourceCard({
  icon,
  title,
  subtitle,
  children,
  accentColor = "sky",
  awsConsoleUrl,
}: {
  icon: React.ReactNode;
  title: string;
  subtitle: string;
  children: React.ReactNode;
  accentColor?: string;
  awsConsoleUrl?: string;
}) {
  const [expanded, setExpanded] = useState(true);
  const borderColor = accentColor === "emerald" ? "border-emerald-500/20" : accentColor === "violet" ? "border-violet-500/20" : accentColor === "amber" ? "border-amber-500/20" : "border-sky-500/20";
  const iconColor = accentColor === "emerald" ? "text-emerald-400" : accentColor === "violet" ? "text-violet-400" : accentColor === "amber" ? "text-amber-400" : "text-sky-400";

  return (
    <div className={`card border ${borderColor}`}>
      <div className="flex items-center justify-between mb-3 cursor-pointer" onClick={() => setExpanded(!expanded)}>
        <div className="flex items-center gap-2.5">
          <span className={iconColor}>{icon}</span>
          <div>
            <p className="text-sm font-semibold text-white">{title}</p>
            <p className="text-xs text-gray-500">{subtitle}</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          {awsConsoleUrl && expanded && (
            <a
              href={awsConsoleUrl}
              target="_blank"
              rel="noopener noreferrer"
              onClick={(e) => e.stopPropagation()}
              className="text-xs text-gray-500 hover:text-sky-400 flex items-center gap-1 transition-colors"
            >
              AWS Console <ExternalLink className="w-3 h-3" />
            </a>
          )}
          {expanded ? <ChevronUp className="w-4 h-4 text-gray-600" /> : <ChevronDown className="w-4 h-4 text-gray-600" />}
        </div>
      </div>
      {expanded && <div className="mt-1">{children}</div>}
    </div>
  );
}

export function ResourceOutputs({ outputs, projectName, awsRegion, awsAccountId }: Props) {
  const hasAny = Object.keys(outputs).some(
    (k) => k !== "github_workflow_yaml" && outputs[k as keyof ResourceOutputs]
  );

  if (!hasAny) return null;

  const downloadEnv = () => {
    const lines: string[] = [
      `# Generated by InfraReady — ${new Date().toISOString()}`,
      `# Project: ${projectName} | Region: ${awsRegion}`,
      `# Environment: production`,
      "",
    ];

    if (outputs.app_url) {
      lines.push("# ── App ──────────────────────────────────────────");
      lines.push(`APP_URL=${outputs.app_url}`);
      lines.push("");
    }
    if (outputs.db_endpoint) {
      lines.push("# ── Database ─────────────────────────────────────");
      lines.push(`DATABASE_HOST=${outputs.db_endpoint}`);
      lines.push(`DATABASE_PORT=${outputs.db_port ?? 5432}`);
      lines.push(`DATABASE_NAME=${outputs.db_name ?? "app"}`);
      lines.push(`DATABASE_URL=postgresql://infraready:YOUR_PASSWORD@${outputs.db_endpoint}:${outputs.db_port ?? 5432}/${outputs.db_name ?? "app"}`);
      if (outputs.db_secret_arn) lines.push(`DATABASE_SECRET_ARN=${outputs.db_secret_arn}`);
      lines.push("");
    }
    if (outputs.cdn_url) {
      lines.push("# ── Storage / CDN ────────────────────────────────");
      lines.push(`CDN_URL=${outputs.cdn_url}`);
      if (outputs.bucket_name) lines.push(`S3_BUCKET=${outputs.bucket_name}`);
      lines.push(`S3_REGION=${awsRegion}`);
      lines.push("");
    }
    if (outputs.ecr_url) {
      lines.push("# ── Container Registry ───────────────────────────");
      lines.push(`ECR_REPOSITORY=${outputs.ecr_url}`);
      lines.push(`AWS_REGION=${awsRegion}`);
      lines.push("");
    }
    if (outputs.cluster_name) {
      lines.push("# ── ECS ──────────────────────────────────────────");
      lines.push(`ECS_CLUSTER=${outputs.cluster_name}`);
      if (outputs.service_name) lines.push(`ECS_SERVICE=${outputs.service_name}`);
      lines.push("");
    }
    if (outputs.vpc_id) {
      lines.push("# ── Network ──────────────────────────────────────");
      lines.push(`VPC_ID=${outputs.vpc_id}`);
      lines.push(`AWS_REGION=${awsRegion}`);
    }

    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `.env.${projectName.toLowerCase().replace(/\s+/g, "-")}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const consoleBase = `https://${awsRegion}.console.aws.amazon.com`;

  return (
    <div className="card">
      <div className="flex items-center justify-between mb-5">
        <div>
          <h2 className="text-sm font-semibold text-gray-300 uppercase tracking-wide">
            Deployed Infrastructure
          </h2>
          <p className="text-xs text-gray-500 mt-0.5">
            Your resources are live. Copy connection strings or download your .env file.
          </p>
        </div>
        <button
          onClick={downloadEnv}
          className="btn-secondary flex items-center gap-2 text-xs"
        >
          <Download className="w-3.5 h-3.5" />
          Download .env
        </button>
      </div>

      <div className="space-y-3">
        {/* App / ECS */}
        {(outputs.app_url || outputs.ecr_url) && (
          <ResourceCard
            icon={<Server className="w-4 h-4" />}
            title="App (ECS Fargate)"
            subtitle={outputs.cluster_name ?? "Container service"}
            accentColor="sky"
            awsConsoleUrl={outputs.cluster_name
              ? `${consoleBase}/ecs/v2/clusters/${outputs.cluster_name}/services`
              : undefined}
          >
            {outputs.app_url && <OutputRow label="App URL" value={outputs.app_url} />}
            {outputs.ecr_url && <OutputRow label="ECR Repository" value={outputs.ecr_url} />}
            {outputs.cluster_name && <OutputRow label="ECS Cluster" value={outputs.cluster_name} />}
            {outputs.service_name && <OutputRow label="ECS Service" value={outputs.service_name} />}
            {outputs.log_group && <OutputRow label="Log Group" value={outputs.log_group} />}
          </ResourceCard>
        )}

        {/* Database */}
        {outputs.db_endpoint && (
          <ResourceCard
            icon={<Database className="w-4 h-4" />}
            title="Database (RDS PostgreSQL)"
            subtitle={outputs.db_endpoint}
            accentColor="emerald"
            awsConsoleUrl={`${consoleBase}/rds/home?region=${awsRegion}#databases:`}
          >
            <OutputRow label="Host" value={outputs.db_endpoint} />
            <OutputRow label="Port" value={String(outputs.db_port ?? 5432)} />
            {outputs.db_name && <OutputRow label="Database" value={outputs.db_name} />}
            {outputs.db_secret_arn && (
              <OutputRow label="Secret ARN" value={outputs.db_secret_arn} />
            )}
            <div className="mt-3 p-2.5 bg-black/30 rounded-lg">
              <p className="text-xs text-gray-500 mb-1">Connection string</p>
              <div className="flex items-center gap-2">
                <code className="text-xs text-emerald-400 truncate">
                  {`postgresql://infraready:****@${outputs.db_endpoint}:${outputs.db_port ?? 5432}/${outputs.db_name ?? "app"}`}
                </code>
                <CopyButton
                  value={`postgresql://infraready:YOUR_PASSWORD@${outputs.db_endpoint}:${outputs.db_port ?? 5432}/${outputs.db_name ?? "app"}`}
                />
              </div>
            </div>
          </ResourceCard>
        )}

        {/* CDN / Storage */}
        {(outputs.cdn_url || outputs.bucket_name) && (
          <ResourceCard
            icon={<HardDrive className="w-4 h-4" />}
            title="Storage (S3 + CloudFront)"
            subtitle={outputs.bucket_name ?? "Object storage"}
            accentColor="violet"
            awsConsoleUrl={outputs.bucket_name
              ? `${consoleBase}/s3/buckets/${outputs.bucket_name}`
              : undefined}
          >
            {outputs.cdn_url && <OutputRow label="CDN URL" value={outputs.cdn_url} />}
            {outputs.bucket_name && <OutputRow label="S3 Bucket" value={outputs.bucket_name} />}
            <OutputRow label="Region" value={awsRegion} />
          </ResourceCard>
        )}

        {/* VPC */}
        {outputs.vpc_id && (
          <ResourceCard
            icon={<Globe className="w-4 h-4" />}
            title="Network (VPC)"
            subtitle={outputs.vpc_id}
            accentColor="amber"
            awsConsoleUrl={`${consoleBase}/vpcconsole/home?region=${awsRegion}#vpcs:`}
          >
            <OutputRow label="VPC ID" value={outputs.vpc_id} />
            <OutputRow label="Region" value={awsRegion} />
            {Array.isArray(outputs.public_subnet_ids) && outputs.public_subnet_ids.length > 0 && (
              <OutputRow label="Public Subnets" value={(outputs.public_subnet_ids as string[]).join(", ")} />
            )}
            {Array.isArray(outputs.private_subnet_ids) && outputs.private_subnet_ids.length > 0 && (
              <OutputRow label="Private Subnets" value={(outputs.private_subnet_ids as string[]).join(", ")} />
            )}
          </ResourceCard>
        )}

        {/* Security */}
        {outputs.alerts_topic_arn && (
          <ResourceCard
            icon={<Shield className="w-4 h-4" />}
            title="Security Baseline"
            subtitle="GuardDuty + Security Hub + Config"
            accentColor="sky"
            awsConsoleUrl={`${consoleBase}/securityhub/home?region=${awsRegion}`}
          >
            {outputs.alerts_topic_arn && <OutputRow label="Alerts SNS Topic" value={outputs.alerts_topic_arn} />}
          </ResourceCard>
        )}

        {/* GitHub workflow */}
        {outputs.github_workflow_yaml && (
          <div className="card border border-white/[0.06]">
            <div className="flex items-center justify-between mb-2">
              <p className="text-sm font-semibold text-white">GitHub Actions Workflow</p>
              <button
                onClick={() => {
                  navigator.clipboard.writeText(outputs.github_workflow_yaml!);
                }}
                className="btn-secondary text-xs flex items-center gap-1.5"
              >
                <Copy className="w-3 h-3" /> Copy YAML
              </button>
            </div>
            <p className="text-xs text-gray-500 mb-3">
              Add this to <code className="text-sky-400">.github/workflows/deploy.yml</code> in your repo to enable auto-deploy on push.
            </p>
            <pre className="text-xs text-gray-400 bg-black/40 rounded-lg p-3 overflow-x-auto max-h-48">
              {outputs.github_workflow_yaml}
            </pre>
          </div>
        )}
      </div>
    </div>
  );
}
